In [ ]:
Submitted By- Sannidhi Bookseller

# Guided project: Thanksgiving data analysis.

## Introduction to the dataset

- Import the pandas library.
- Use the pandas.read_csv() function to read the thanksgiving.csv file.
>- Specify in the function parameters the argument encoding='latin-1' because this dataset is not encoded normally.
>- Assign the dataframe to the variable data
- Display the first lines of data.
- Display the column names with the columns attribute.

In [12]:
import pandas as pd
import numpy as np
data = pd.read_csv('thanksgiving.csv', encoding = 'latin-1')
data.head(1)

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic

In [11]:
list(data.columns)

['RespondentID',
 'Do you celebrate Thanksgiving?',
 'What is typically the main dish at your Thanksgiving dinner?',
 'What is typically the main dish at your Thanksgiving dinner? - Other (please specify)',
 'How is the main dish typically cooked?',
 'How is the main dish typically cooked? - Other (please specify)',
 'What kind of stuffing/dressing do you typically have?',
 'What kind of stuffing/dressing do you typically have? - Other (please specify)',
 'What type of cranberry saucedo you typically have?',
 'What type of cranberry saucedo you typically have? - Other (please specify)',
 'Do you typically have gravy?',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Brussel sprouts',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Carrots',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cauliflower',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Corn',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cornbread',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Fruit salad',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Green beans/green bean casserole',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Macaroni and cheese',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Mashed potatoes',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Rolls/biscuits',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Squash',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Vegetable salad',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Yams/sweet potato casserole',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
 'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Buttermilk',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Cherry',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Chocolate',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Coconut cream',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Key lime',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Peach',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Sweet Potato',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - None',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Apple cobbler',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Blondies',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Brownies',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Carrot cake',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cheesecake',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cookies',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Fudge',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Ice cream',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Peach cobbler',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - None',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify)',
 'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify).1',
 'Do you typically pray before or after the Thanksgiving meal?',
 'How far will you travel for Thanksgiving?',
 "Will you watch any of the following programs on Thanksgiving? Please select all that apply. - Macy's Parade",
 'What\'s the age cutoff at your "kids\' table" at Thanksgiving?',
 'Have you ever tried to meet up with hometown friends on Thanksgiving night?',
 'Have you ever attended a "Friendsgiving?"',
 'Will you shop any Black Friday sales on Thanksgiving Day?',
 'Do you work in retail?',
 'Will you employer make you work on Black Friday?',
 'How would you describe where you live?',
 'Age',
 'What is your gender?',
 'How much total combined money did all members of your HOUSEHOLD earn last year?',
 'US Region']

## Filtering data

- Use the Series.value_counts() method to display the response count for each category in the 'Do you celebrate Thanksgiving?' column.
- Filter and save all rows of the dataframe data for which the answer to the 'Do you celebrate Thanksgiving?' question is 'Yes'.
- Assign this new dataframe to data and display it.

In [13]:
df = data['Do you celebrate Thanksgiving?'].value_counts()
df

Yes    980
No      78
Name: Do you celebrate Thanksgiving?, dtype: int64

In [15]:
new_dataframe = data['Do you celebrate Thanksgiving?'] == 'Yes'
new_dataframe = data[new_dataframe]
new_dataframe

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1053,4335944082,Yes,Turkey,NaN,Roasted,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,Yes,No,No,NaN,Rural,30 - 44,Female,"$100,000 to $124,999",Mountain
1054,4335943173,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,No,No,NaN,Suburban,60+,Female,"$50,000 to $74,999",Pacific
1055,4335943060,Yes,Other (please specify),Duck,Baked,NaN,Rice-based,NaN,None,NaN,...,Yes,Yes,Yes,No,NaN,Urban,60+,Male,"$100,000 to $124,999",Pacific
1056,4335934708,Yes,Turkey,NaN,Baked,NaN,None,NaN,Homemade,NaN,...,Yes,No,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1057,4335894916,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,Yes,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN

## Exploring thanksgiving dinners

- Use the Series.value_counts() method to display how many times each result appears for the 'What is typically the main dish at your Thanksgiving dinner?' question and column.
- Display the 'Do you typically have gravy? column for rows in the dataframe data for which the 'What is typically the main dish at your Thanksgiving dinner? column is set to 'Tofurkey' for tofu turkey.
>- Create a filter that selects only those rows in the dataframe data where 'What is typically the main dish at your Thanksgiving dinner?' is set to 'Tofurkey'.
>- Assign the result to the variable tofurkey
>- Display the 'Do you typically have gravy?' column of this new tofurkey dataframe.

In [16]:
print(data['What is typically the main dish at your Thanksgiving dinner?'].value_counts())

Turkey                    859
Other (please specify)     35
Ham/Pork                   29
Tofurkey                   20
Chicken                    12
Roast beef                 11
I don't know                5
Turducken                   3
Name: What is typically the main dish at your Thanksgiving dinner?, dtype: int64

In [18]:
tofurkey = data[data['What is typically the main dish at your Thanksgiving dinner?'] == 'Tofurkey']
tofurkey

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific
33,4337771439,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Suburban,30 - 44,Male,"$50,000 to $74,999",Middle Atlantic
69,4337553422,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,Yes,No,No,NaN,Urban,18 - 29,Male,"$10,000 to $24,999",West South Central
72,4337540484,Yes,Tofurkey,NaN,I don't know,NaN,Bread-based,NaN,None,NaN,...,No,No,Yes,No,NaN,Suburban,18 - 29,Male,Prefer not to answer,Pacific
77,4337490067,Yes,Tofurkey,NaN,Roasted,NaN,None,NaN,None,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,Prefer not to answer,East North Central
145,4337191550,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,No,No,NaN,Urban,30 - 44,Female,"$125,000 to $149,999",West South Central
175,4337139327,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,No,No,No,No,NaN,Rural,30 - 44,Female,"$75,000 to $99,999",West North Central
218,4337078951,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,Yes,No,No,NaN,Suburban,30 - 44,Female,"$200,000 and up",Mountain
243,4337044348,Yes,Tofurkey,NaN,Other (please specify),various ways,Bread-based,NaN,Canned,NaN,...,No,No,No,No,NaN,Urban,60+,Female,"$100,000 to $124,999",South Atlantic
275,4336997445,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,No,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Middle Atlantic
393,4336894719,Yes,Tofurkey,NaN,Roasted,NaN,Bread-based,NaN,Canned,NaN,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$25,000 to $49,999",New England
399,4336891075,Yes,Tofurkey,NaN,Roasted,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Suburban,60+,Female,"$125,000 to $149,999",South Atlantic
571,4336760110,Yes,Tofurkey,NaN,Roasted,NaN,Bread-based,NaN,None,NaN,...,No,No,No,No,NaN,Suburban,18 - 29,Female,Prefer not to answer,South Atlantic
594,4336736562,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,No,No,No,No,NaN,Rural,45 - 59,Female,"$175,000 to $199,999",Middle Atlantic
628,4336692873,Yes,Tofurkey,NaN,Baked,NaN,None,NaN,Homemade,NaN,...,No,No,Yes,No,NaN,Suburban,60+,Female,"$25,000 to $49,999",Middle Atlantic
774,4336400854,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,Yes,No,Yes,Yes,Suburban,45 - 59,Female,"$75,000 to $99,999",Mountain
820,4336238126,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,No,No,No,No,NaN,Urban,18 - 29,Female,"$10,000 to $24,999",Pacific
837,4336175740,Yes,Tofurkey,NaN,Baked,NaN,None,NaN,None,NaN,...,No,No,Yes,Yes,No,Suburban,18 - 29,Female,"$25,000 to $49,999",West North Central
860,4336121663,Yes,Tofurkey,NaN,Baked,NaN,Rice-based,NaN,Other (please specify),freshly made at a deli counter,...,No,Yes,No,No,NaN,Urban,30 - 44,Female,"$25,000 to $49,999",Pacific
953,4336005220,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Suburban,30 - 44,Male,"$0 to $9,999",Middle Atlantic

In [19]:
tofurkey[['Do you typically have gravy?' ]]

    Do you typically have gravy?
4                            Yes
33                           Yes
69                            No
72                            No
77                           Yes
145                          Yes
175                          Yes
218                           No
243                          Yes
275                           No
393                          Yes
399                          Yes
571                          Yes
594                          Yes
628                           No
774                           No
820                           No
837                          Yes
860                           No
953                          Yes

## Dessert trends for Thanksgiving ##

- Create a Series object indicating with booleans the values of the column 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple' which are null. Assign the result to the variable apple_isnull.
- Create a Series object that uses booleans to indicate the values in the column 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin' which are null. Assign the result to the pumpkin_isnull variable.
- Create a Series object with booleans indicating the values in the column 'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan' which are null. Assign the result to the variable pecan_isnull.
- Combine these 3 Series objects with the & operator and assign the result to the pies variable.
- Display the unique values and how many times they appear in the pies column.

In [20]:
apple_isnull = pd.isnull(data['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple'])
apple_isnull

0       False
1       False
2       False
3        True
4       False
        ...
1053     True
1054     True
1055    False
1056     True
1057     True
Name: Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple, Length: 1058, dtype: bool

In [27]:
pumpkin_isnull = pd.isnull(data['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin'])
pumpkin_isnull

0        True
1       False
2       False
3       False
4       False
        ...
1053    False
1054    False
1055     True
1056     True
1057     True
Name: Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin, Length: 1058, dtype: bool

In [28]:
pecan_isnull = pd.isnull(data['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan'])
pecan_isnull

0        True
1        True
2       False
3       False
4        True
        ...
1053    False
1054     True
1055     True
1056     True
1057     True
Name: Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan, Length: 1058, dtype: bool

In [29]:
ate_pies = apple_isnull & pumpkin_isnull & pecan_isnull
ate_pies

0       False
1       False
2       False
3       False
4       False
        ...
1053    False
1054    False
1055    False
1056     True
1057     True
Length: 1058, dtype: bool

In [30]:
print(ate_pies.value_counts())

False    876
True     182
dtype: int64

## Convert age to a numerical value ##

- Write a function that converts a string into an integer value. This will convert the values in the 'Age' column to integers. This function will take as parameter a string of characters (the current values of the column 'Age').
>- Use the isnull() function to check if the values are null. Add an if condition that returns 'None' if the value is null.
>- Separate strings by space (' ') and extract the first element from the resulting list (split() method)
>- Replace the '+' character in the result with an empty string to remove it (replace() method).
>- use int() to convert the result to an integer
>- Return the result
- Use the Series.apply() method to apply the function to each value in the 'Age' column of the dataframe data.
>- Assign the result to the new int_age column of the dataframe data.
- Call the Series.describe() method on the 'int_age' column of the dataframe data and display the result.

In [32]:
df4 = data['Age'].value_counts()
df4

45 - 59    286
60+        264
30 - 44    259
18 - 29    216
Name: Age, dtype: int64

In [33]:
def str_to_int(age_str):

    if pd.isnull(age_str):    # Use the isnull() function to check if the value is null. If it is, return None.

        return None

    age_str = age_str.split(' ')[0]# Split the string on the space character (), and extract the first item of the resulting list.

    age_str = age_str.replace('+', '') # Replace the + character in the result with an empty string to remove it.

    return int(age_str) # Use int() to convert the result to an integer.

data['int_age'] = data['Age'].apply(str_to_int) # Use the pandas.Series.apply() method to apply the function to each value in the Age column of data.

data['int_age'].describe() # Call the pandas.Series.describe() method on the int_age column of data, and display the result.

count    1025.000000
mean       39.383415
std        15.398493
min        18.000000
25%        30.000000
50%        45.000000
75%        60.000000
max        60.000000
Name: int_age, dtype: float64

## Convert income to numerical values

- Write a function to convert income to a single integer format value.
>- Use the isnull() function to check if the value is null. If it is, return 'None'.
>- Separate the string using space as delimiter and extract the first element from the resulting list.
>- If the result is 'Prefer', return 'none'.
>- Replace the characters '$' and ',' with empty strings to delete them.
>- Use int() to convert the result to an integer
>- Return the result
- Use the Series.apply() method to apply the above function to each value in the 'How much total combined money did all members of your HOUSEHOLD earn last year?' column of the dataframe data.
>- Assign the result to the new column 'int_income' in the dataframe data.
- Call the Series.describe() method to the int_income column of the dataframe data and display the result.

In [27]:
print(data['How much total combined money did all members of your HOUSEHOLD earn last year?'].value_counts())

$25,000 to $49,999      180
Prefer not to answer    136
$50,000 to $74,999      135
$75,000 to $99,999      133
$100,000 to $124,999    111
$200,000 and up          80
$10,000 to $24,999       68
$0 to $9,999             66
$125,000 to $149,999     49
$150,000 to $174,999     40
$175,000 to $199,999     27
Name: How much total combined money did all members of your HOUSEHOLD earn last year?, dtype: int64

In [28]:
def income_to_int(income_str):
    if pd.isnull(income_str):  # Use the isnull() function to check if the value is null. If it is, return None.
        return None
    income_str = income_str.split(' ')[0] # Split the string on the space character (), and extract the first item of the resulting list.
    if income_str == 'Prefer':
        return None
    income_str = income_str.replace('$', '')
    income_str = income_str.replace(',', '')
    return int(income_str)

data['int_income'] = data['How much total combined money did all members of your HOUSEHOLD earn last year?'].apply(income_to_int)
print(data['int_income'].describe())

count       889.000000
mean      74077.615298
std       59360.742902
min           0.000000
25%       25000.000000
50%       50000.000000
75%      100000.000000
max      200000.000000
Name: int_income, dtype: float64

## Correlation between distance and income

- Watch how people earning less than 150,000 dollars travel.
>- Filter data by selecting only 'int_income' values below $150,000.
>- Select the column 'How far will you travel for Thanksgiving? taking into account the filter
>- Use the value_counts() method to count how many times each value appears in the column.
>- Display the results
- Do the same with people earning more than 150,000 dollars.

In [29]:
df5 = data[data['int_income']< 150000]['How far will you travel for Thanksgiving?'].value_counts()
df5

Thanksgiving is happening at my home--I won't travel at all                         281
Thanksgiving is local--it will take place in the town I live in                     203
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    150
Thanksgiving is out of town and far away--I have to drive several hours or fly       55
Name: How far will you travel for Thanksgiving?, dtype: int64

In [30]:
df5 = data[data['int_income'] > 150000]['How far will you travel for Thanksgiving?'].value_counts()

df5

Thanksgiving is happening at my home--I won't travel at all                         49
Thanksgiving is local--it will take place in the town I live in                     25
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    16
Thanksgiving is out of town and far away--I have to drive several hours or fly      12
Name: How far will you travel for Thanksgiving?, dtype: int64

## Link between spending Thanksgiving with friends with age and income ##

- Generate a pivot table showing the average age of respondents for each category of the questions 'Have you ever tried to meet up with hometown friends on Thanksgiving night? and 'Have you ever attended a "Friendsgiving?"'.
>- Call the pivot_table() method on the dataframe data
>- Set the 'index' parameter to 'Have you ever tried to meet up with hometown friends on Thanksgiving night?'.
>- Set the 'columns' parameter to 'Have you ever attended a "Friendsgiving?"'.
>- Set the 'values' parameter to 'int_age'.
>- Display the results
- Do the same for revenues with these two questions.

In [31]:

data.pivot_table(
    index = "Have you ever tried to meet up with hometown friends on Thanksgiving night?",
    columns = 'Have you ever attended a "Friendsgiving?"',
    values = 'int_income'
)

Have you ever attended a "Friendsgiving?"                     No           Yes
Have you ever tried to meet up with hometown fr...
No                                                  78914.549654  72894.736842
Yes                                                 78750.000000  66019.736842

In [34]:
data.pivot_table(
    index = "Have you ever tried to meet up with hometown friends on Thanksgiving night?",
    columns = 'Have you ever attended a "Friendsgiving?"',
    values = 'int_age'
)

Have you ever attended a "Friendsgiving?"                  No        Yes
Have you ever tried to meet up with hometown fr...
No                                                  42.283702  37.010526
Yes                                                 41.475410  33.976744