# Manipulating data with the Pandas library
- Import the pandas library.
- Read the file "food_info.csv" in a dataframe called food_info.
- Use the Dataframe.columns attribute followed by the Index.tolist() method to return a list containing all food_info column names.
- Assign the resulting list to the col_names variable and use the print() function to display the column names.
- Finally display the first 3 elements of food_info.

In [2]:
import pandas as pd
df = pd.read_csv("food_info.csv")
df

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,1080.0,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,157.0,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,5.0,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,100.0,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,100.0,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0

In [10]:
# Use the Dataframe.columns attribute followed by the Index.tolist() method to return a list containing all food_info column names.
col_names = df.columns.tolist()
print(col_names)

['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)', 'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)', 'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)', 'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)', 'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)', 'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)', 'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)']

In [12]:
df.head(3)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0

## Transform a column

- Divide the column "Sodium_(mg)" by 1000 to convert this column to grams and assign the result to the variable sodium_grams.
- Multiply the column "Sugar__Tot_(g)" by 1000 to convert to milligrams and assign the result to the variable sugar_milligrams.

In [13]:
df.assign((Sodium_g) = df['Sodium_(mg)']/1000)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Sodium_g
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.643
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.659
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.002
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,1.146
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,4.450
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.667
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.058
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.070
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.068

In [16]:
df.assign((sugar_miligram) = df['Sugar_Tot_(g)']*1000)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),sugar_miligram
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,60.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,60.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.0
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,500.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,510.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,0.0
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.0
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,73200.0
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.0
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.0

## Mathematical operations between columns

- Divide the column "Protein_(g)" by the column "Water_(g)" and assign the result to the variable grams_of_protein_per_gram_of_water.
- Add the columns "Calcium_(mg)" and "Iron_(mg)" and assign the result to the variable milligrams_of_calcium_and_iron.
- Display the results.

In [19]:
df.assign((grams_of_protein_per_gram_of_water) = df['Protein_(g)']/df['Water_(g)'])

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),grams_of_protein_per_gram_of_water
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.053560
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.053560
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,1.166667
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.504598
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.565313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,0.430233
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.292384
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.000000
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.203283
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.252229

In [20]:
df.assign((milligrams_of_calcium_and_iron) = df['Calcium_(mg)'] + df['Iron_(mg)'])

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),milligrams_of_calcium_and_iron
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,24.02
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,24.16
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,4.00
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,528.31
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,674.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,67.40
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,10.58
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,16.60
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,13.50
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,119.40

## Create a nutritional index

Score = 2 x (Protein_(g)) - 0.75 x (Lipid_Tot_(g))

- Multiply the column "Protein_(g)" by 2 and assign the result to the variable protein.
- Multiply the column "Lipid_Tot_(g)" by -0.75 and assign the result to the variable fat.
- Add the variables together and assign the result to the variable rating.
- Display the result.

In [23]:
df.assign((protein) = (df['Protein_(g)']*2)-(0.75* df['Lipid_Tot_(g)']))
#df.assign((fat) = df['Lipid_Tot_(g)'])
#df.assign((score) = (df['protein']-0.75)*df['fat'])

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),protein
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,-59.1325
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,-59.1325
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,-74.0500
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,21.2450
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,24.2200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,18.1750
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,40.4500
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.0000
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,31.1500
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,39.2250

## Standardize columns

- Normalize the values in the column "protein_(g)" and assign the result to the variable normalized_protein.
- Normalize the values in the "Lipid_Tot_(g)" column and assign the result to the normalized_fat variable.

In [46]:
#normalized_df=(df-df.min())/(df.max()-df.min())
max_value = df["Protein_(g)"].max()
min_value = df["Protein_(g)"].min()
df.assign((normalized_protein) = (df['Protein_(g)']-min_value)/(max_value - min_value))

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),normalized_protein
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.009624
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.009624
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.003170
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.242301
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.263134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,0.209466
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.232563
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.000000
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.182292
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.224185

In [29]:
max_value = df["Lipid_Tot_(g)"].max()
min_value = df["Lipid_Tot_(g)"].min()
df.assign((normalized_fat ) = (df['Lipid_Tot_(g)']-min_value)/(max_value - min_value))

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),normalized_protein
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.8111
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.8111
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.9948
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.2874
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.2968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,0.2510
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.0084
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.0000
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.0140
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.0050

## Create a new column

- Assign the normalized column represented by the normalized_protein variable to the new column that will be named "Normalized_Protein" in the food_info dataframe.
- Assign the normalized column represented by the normalized_fat variable to the new column named "Normalized_Fat" in the food_info dataframe.
- Display the first 5 values of the dataframe food_info.

In [59]:
max_value = df["Protein_(g)"].max()
min_value = df["Protein_(g)"].min()
normalized_protein = df['Protein_(g)']-min_value/(max_value - min_value)
df["Normalized_Protein"] = normalized_protein
df

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),a,normalized_protein,Normalized_protein,Normalized_fat,Normalized_Protein
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,7.0,51.368,21.021,3.043,215.0,0,0.85,0.85,81.11,0.85
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,7.0,50.489,23.426,3.012,219.0,0,0.85,0.85,81.11,0.85
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,8.6,61.924,28.732,3.694,256.0,0,0.28,0.28,99.48,0.28
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,2.4,18.669,7.778,0.800,75.0,0,21.40,21.40,28.74,21.40
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,2.5,18.764,8.598,0.784,94.0,0,23.24,23.24,29.68,23.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,7.8,7.148,8.320,6.210,95.0,0,18.50,18.50,25.10,18.50
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,0.0,0.218,0.082,0.222,41.0,0,20.54,20.54,0.84,20.54
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.000,0.000,0.000,0.0,0,0.00,0.00,0.00,0.00
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,0.1,0.361,0.259,0.252,50.0,0,16.10,16.10,1.40,16.10
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,0.1,0.127,0.088,0.170,50.0,0,19.80,19.80,0.50,19.80

In [60]:
max_value = df["Lipid_Tot_(g)"].max()
min_value = df["Lipid_Tot_(g)"].min()
normalized_fat = df['Lipid_Tot_(g)']-min_value/(max_value - min_value)
df['Normalized_Fat'] = normalized_fat
df

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),a,normalized_protein,Normalized_protein,Normalized_fat,Normalized_Protein,Normalized_Fat
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,51.368,21.021,3.043,215.0,0,0.85,0.85,81.11,0.85,81.11
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,50.489,23.426,3.012,219.0,0,0.85,0.85,81.11,0.85,81.11
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,61.924,28.732,3.694,256.0,0,0.28,0.28,99.48,0.28,99.48
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,18.669,7.778,0.800,75.0,0,21.40,21.40,28.74,21.40,28.74
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,18.764,8.598,0.784,94.0,0,23.24,23.24,29.68,23.24,29.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,7.148,8.320,6.210,95.0,0,18.50,18.50,25.10,18.50,25.10
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,0.218,0.082,0.222,41.0,0,20.54,20.54,0.84,20.54,0.84
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.000,0.000,0.000,0.0,0,0.00,0.00,0.00,0.00,0.00
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,0.361,0.259,0.252,50.0,0,16.10,16.10,1.40,16.10,1.40
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,0.127,0.088,0.170,50.0,0,19.80,19.80,0.50,19.80,0.50

In [58]:
# Display the first 5 values of the dataframe food_info.
df.head(5)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),a,normalized_protein,Normalized_protein,Normalized_fat
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,60.0,7.0,51.368,21.021,3.043,215.0,0,0.85,0.85,81.11
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,60.0,7.0,50.489,23.426,3.012,219.0,0,0.85,0.85,81.11
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,73.0,8.6,61.924,28.732,3.694,256.0,0,0.28,0.28,99.48
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,21.0,2.4,18.669,7.778,0.800,75.0,0,21.40,21.40,28.74
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,22.0,2.5,18.764,8.598,0.784,94.0,0,23.24,23.24,29.68

## Create a column for the standardized nutrition index

Score = 2 x Normalized_Protein - 0.75 x Normalized_Fat

- Use the Normalized_Protein and Normalized_Fat columns with this formula to create a new column named Norm_Nutr_Index.

In [76]:
df.assign(score = (df['Normalized_Protein']*2)-(0.75* df['Normalized_Fat']))

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),a,normalized_protein,Normalized_protein,Normalized_fat,Normalized_Protein,Normalized_Fat,score
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,21.021,3.043,215.0,0,0.85,0.85,81.11,0.85,81.11,-59.1325
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,23.426,3.012,219.0,0,0.85,0.85,81.11,0.85,81.11,-59.1325
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,28.732,3.694,256.0,0,0.28,0.28,99.48,0.28,99.48,-74.0500
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,7.778,0.800,75.0,0,21.40,21.40,28.74,21.40,28.74,21.2450
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,8.598,0.784,94.0,0,23.24,23.24,29.68,23.24,29.68,24.2200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,8.320,6.210,95.0,0,18.50,18.50,25.10,18.50,25.10,18.1750
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,0.082,0.222,41.0,0,20.54,20.54,0.84,20.54,0.84,40.4500
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.000,0.000,0.0,0,0.00,0.00,0.00,0.00,0.00,0.0000
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,0.259,0.252,50.0,0,16.10,16.10,1.40,16.10,1.40,31.1500
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,0.088,0.170,50.0,0,19.80,19.80,0.50,19.80,0.50,39.2250

## Sort a DataFrame

- Replace the dataframe food_info by sorting against the Norm_Nutr_Index column in descending order (from largest to smallest)

In [78]:
df.sort_values('score', ascending = False)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),a,normalized_protein,Normalized_protein,Normalized_fat,Normalized_Protein,Normalized_Fat,score
4991,16423,SOY PROT ISOLATE K TYPE CRUDE PROT BASIS,4.98,321,88.32,0.53,3.58,2.59,2.0,0.0,...,0.101,0.258,0.0,0,88.32,88.32,0.53,88.32,0.53,176.2425
6155,19177,GELATINS DRY PDR UNSWTND,13.00,335,85.60,0.10,1.30,0.00,0.0,0.0,...,0.060,0.010,0.0,0,85.60,85.60,0.10,85.60,0.10,171.1250
216,1258,EGG WHITE DRIED STABILIZED GLUCOSE RED,6.53,362,84.63,0.48,3.63,4.72,0.0,0.0,...,0.173,0.070,20.0,0,84.63,84.63,0.48,84.63,0.48,168.9000
124,1136,EGG WHITE DRIED PDR STABILIZED GLUCOSE RED,8.54,376,82.40,0.04,4.55,4.47,0.0,0.0,...,0.000,0.000,0.0,0,82.40,82.40,0.04,82.40,0.04,164.7700
8152,35055,SEAL BEARDED (OOGRUK) MEAT DRIED (ALASKA NATIVE),11.60,351,82.60,2.30,3.50,0.00,0.0,0.0,...,1.330,0.370,NaN,0,82.60,82.60,2.30,82.60,2.30,163.4750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,4534,OIL BABASSU,0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,11.400,1.600,0.0,0,0.00,0.00,100.00,0.00,100.00,-75.0000
669,4532,OIL HAZELNUT,0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,78.000,10.200,0.0,0,0.00,0.00,100.00,0.00,100.00,-75.0000
668,4531,OIL SOYBN LECITHIN,0.00,763,0.00,100.00,0.00,0.00,0.0,0.0,...,10.977,45.318,0.0,0,0.00,0.00,100.00,0.00,100.00,-75.0000
667,4530,OIL APRICOT KERNEL,0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,60.000,29.300,0.0,0,0.00,0.00,100.00,0.00,100.00,-75.0000
666,4529,OIL ALMOND,0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,69.900,17.400,0.0,0,0.00,0.00,100.00,0.00,100.00,-75.0000